print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")

print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")
print("my name is sudh")

